version: '3'

services:
  custom_web_page:
    image: proxy
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html/
  webapp:
    image: tutum/hello-world
    ports:
      - "80"